# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ndcCBnTwbcepDNAbyp5-EnzGLIHDiccN
"""

# Conversion de binario a decimal (0,1)
a = '1001'      #9 en decimal
print(int(a,2)) #Con el 2 le digo que es un numero de base 2

print(int('10000000',2))

# Conversion de hexadecimal a decimal (0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F)
b = 'A9'      #1010 1001
print(int(b,16))

# Conversion de octal a decimal (0,1,2,3,4,5,6,7)
c = '36'      #011 110
print(int(c,8))

# Conversion de decimal a binario
d = bin(9)
print(d)

# Conversion de decimal a octal
e = oct(30)
print(e)

# Conversion de decimal a hexadecimal
f = hex(169)
print(f)

# Conversion de base 7 a decimal
print(int('012',7))

# Conversion de binario a hexadecimal
print(hex(0b1001))

# eval()
x = 1
print(eval('x + 8'))

x = 25
print(eval('x**2 + 3'))

# max()
print(ord('h'))
print(ord('2'))
print(max(['h','2']))

# min()
print(min([1,2,8,4,23]))

# sum()

a = [1,8,9,12,5]
print(sum(a))

# ord()   # Devuelve el valor ASCII de una cadena o caracter

print(ord('1'))

#print(ord('111'))

# Realizar un programa que capture dos números enteros ingresados por el usuario y realice las
# operaciones aritméticas básicas (suma, resta, multiplicación y división)

num1,num2 = map(int,input().split())

suma = num1 + num2
resta = num1 - num2
mul = num1 * num2
div = num1 / num2 
print(suma,resta,mul,div)

# Realizar un programa que capture dos números enteros ingresados por el usuario y realice las
# operaciones aritméticas básicas (suma, resta, multiplicación y división)

def operaciones(a,b):
  suma = a + b
  resta = a - b
  mul = a * b
  div = a / b
  return suma,resta,mul,div


num1,num2 = map(int,input().split())
resultado = operaciones(num1,num2)
print(resultado)
suma1,resta1,mul1,div1 = operaciones(num1,num2)
print(suma1,resta1,mul1,div1)
print(suma1)
print(resta1)
print(mul1)
print(div1)

# Realizar un programa que capture dos números reales ingresados por el usuario y la operacion aritmetica que va a realizar.
# Las operaciones aritméticas pueden ser: (suma(1), resta(2), multiplicación(3) y división(4))

def operaciones(a,b,oper):
  if (oper == '1'):
    res = a + b
  elif (oper == '2'):
    res = a - b
  elif (oper == '3'):
    res = a * b
  elif (oper == '4'):
    res = a / b
  else:
    res = 'Operacion incorrecta'
  return res

oper1 = input('Ingrese el numero de operacion que va a realizar: (1)suma, (2)resta, (3)multiplicación y (4)division: ')
num1,num2 = map(float,input().split())
print(operaciones(num1,num2,oper1))

# y = abs(a)**2

def absoluto(a):
  if a > 0:
    abs1 = a
  else:
    abs1 = -a
  return abs1


def potencia(base,exponente):
  mul = 1
  for i in range(exponente):
    mul *= base
  return mul

print(absoluto(-3))
print(potencia(6,3))

a = 3
y = potencia(absoluto(a),2)
print(y)

